### ISSUE TITLE
Weird icon rendering

### ISSUE THREAD

**Issue by PrinzKenny1** [andronasef/iconify_flutter#7]
Hey, I noticed some weird icon rendering when using arrow_left... I tested some Icon Packs (AkarIcons, Charm) and in both the arrow looks like this:

![grafik](https://user-images.githubusercontent.com/20337565/178165268-5baf9bf2-23d8-4aa9-9475-de0100c4aaa9.png)

But it should look like this:

![grafik](https://user-images.githubusercontent.com/20337565/178165234-1566dab9-3564-48f2-afd0-2046732072b9.png)

Same applies to the arrows pointing down, up and right. I don't know if more icons are affected.

I'm using Flutter 3.0.4

**Comment by andronasef** [comment]
Sorry for let you waiting long 🙂
But I didn't get any notification about this issue. Sorry 😐

This issue is caused by the SVG renderer package 📦 that I use.

I will try to solve this issue soon 🔜

Thanks you for letting me know ❤️

**Comment by kencana16** [comment]
i think the issue is from svg code. 

AkarIcons.arrow_left is containing value like this 
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m11 5-7 7 7 7m-7-7h16"/></svg>`
and rendered like this 
![image](https://user-images.githubusercontent.com/44537998/184329937-6149d43f-f697-4ee6-b9db-de80e4ddfc0d.png)


but when I change to `fill="transparent"` it looks like this 
![image](https://user-images.githubusercontent.com/44537998/184330200-da046cdb-9060-4c0d-9864-01949ef1dd9d.png)
